services:
  popod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POCKETBASE_VERSION=0.22.7
        - TARGETOS=linux
        - TARGETARCH=amd64
    # Rewrite command for development mode
    command: serve --http 0.0.0.0:80 --dev --hooksWatch
    ports:
      - 8090:80
    volumes:
      - ./pb_public:/pocketbase/pb_public:ro
      - ./pb_hooks:/pocketbase/pb_hooks:ro
      - ./pb_migrations:/pocketbase/pb_migrations:rw
      - ./pb_data:/pocketbase/pb_data:rw

volumes: {}
  #pb_data: {}